## Introduction to Data Science

#### University of Redlands - DATA 101
#### Prof: Joanna Bieri [joanna_bieri@redlands.edu](mailto:joanna_bieri@redlands.edu)
#### [Class Website: data101.joannabieri.com](https://joannabieri.com/data101.html)

---------------------------------------
# Homework Day 7
---------------------------------------

GOALS:

1. Answer all the questions from the lecture - we will use the scientists data and the grocery data.
2. Analyze data about College majors - your first EDA! (Think of this as a practice exam.)

----------------------------------------------------------

This homework has **9 Questions** and **A Practice Exam**

NOTE:
The practice exam is intended to give you an idea of what an exam in this class might feel like. Remember you will be expected to work on the exam **independently** and submit your work before we get together to work on the exam in class. **15\% of your Exam grade will come from what you can do independently** so start practicing now and get help if you need it!.

In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.io as pio
pio.renderers.defaule = 'colab'

from itables import show

## Lecture Questions

First we will import the data about female scientists.

In [2]:
file1 = 'https://joannabieri.com/introdatascience/data/dates.csv'
DF_dates = pd.read_csv(file1)
file2 = 'https://joannabieri.com/introdatascience/data/professions.csv'
DF_professions = pd.read_csv(file2)
file3 = 'https://joannabieri.com/introdatascience/data/works.csv'
DF_works = pd.read_csv(file3)
show(DF_dates)
show(DF_professions)
show(DF_works)

**Q1** Are each of these data sets Tidy?

**Q2** Do they all contain the same number of observations?

**Q3** What are the five variables?

**Q4** What variable do they have in common - what can we join **on**

**(Click Here)**



## Combining Three Data Sets

You need to think about the order and whether or not you want to keep the maximum number of names or only keep names that are in all the data frames.

In this case we will try to keep the maximal amount of data - the maximum number of names.

1. Combine the professions and works data
2. Then add the dates data

In [3]:
# 1. Combine the professions and works data
DF_scientists = pd.merge(DF_professions,DF_works,on='name',how='left')
DF_scientists
# 2. Then add the dates data
DF_scientists = pd.merge(DF_scientists,DF_dates,on='name',how='left')
DF_scientists

name                          profession  \
0        Ada Lovelace                       Mathematician   
1         Marie Curie               Physicist and Chemist   
2        Janaki Ammal                            Botanist   
3     Chien-Shiung Wu                           Physicist   
4   Katherine Johnson                       Mathematician   
5   Rosalind Franklin                             Chemist   
6          Vera Rubin                          Astronomer   
7         Gladys West                       Mathematician   
8  Flossie Wong-Staal  Virologist and Molecular Biologist   
9     Jennifer Doudna                          Biochemist   

                                           known_for  birth_year  death_year  
0                           first computer algorithm         NaN         NaN  
1  theory of radioactivity,  discovery of element...         NaN         NaN  
2            hybrid species, biodiversity protection      1897.0      1984.0  
3  confim and refine theory of radioactive beta d...      1912.0      1997.0  
4  calculations of orbital mechanics critical to ...      1918.0      2020.0  
5                                                NaN      1920.0      1958.0  
6                           existence of dark matter      1928.0      2016.0  
7  mathematical modeling of the shape of the Eart...      1930.0         NaN  
8  first scientist to clone HIV and create a map ...      1947.0         NaN  
9  one of the primary developers of CRISPR, a gro...      1964.0         NaN

**Q5** What, if anything, would change if you switched to how='right'?

**(Click Here)**

## Combining Two Data Sets - You Try

**Q6** Write code that would combine the professions data and the dates data, but drop any names that don't appear in both.

In [4]:
# Your code here



## Combining Three Data Sets - You Try

**Q7** Try to combine the three data sets together (professions, works, and dates) but instead of doing what we did above, see if you can keep only the names that appeared in all three data sets.

In [5]:
# Your code here



## Case study - Grocery Sales

Below you will load some data about grocery sales and see how joining or merging data can help us answer questions.

In [6]:
file1 = 'https://joannabieri.com/introdatascience/data/purchases.csv'
DF_purchases = pd.read_csv(file1)
file2 = 'https://joannabieri.com/introdatascience/data/prices.csv'
DF_prices = pd.read_csv(file2)
show(DF_purchases)
show(DF_prices)

## Calculate the total revenue

**Q8** Given the data above find the total revenue.

We will have to join the data frames so that we can see the price of what was sold. So first we look for a common column. In this case both data frames have **item** as a column.

Now, think about how to calculate revenue... we need to add up the total money we made, so we need to know the price of each thing sold.

**PAUSE - see if you can write some of the code for this before looking at the cells below**

In [7]:
#

In [8]:
#

In [9]:
#

In [10]:
#

**See the lecture notes if you need heelp figuring this out!**

**Q9** Calculate the revenue per customer? Hint - group by the customer id and then apply the sum().

In [11]:
# Your code here


# Practice Exam - EDA - College Majors

Your solutions should include code written to answer the questions AND words describing the results. For each problem:

1. Write code to get the answers. It is okay to copy and paste from our lecture notes or your homework assignments.
2. Describe what the code output is telling you.
3. Explain any interesting aspects of your results.

------------------------
-------------------------

The first step in the process of turning information into knowledge process is to summarize and describe the raw information - the data.
In this assignment we explore data on college majors and earnings, specifically the data begin the FiveThirtyEight story ["The Economic Guide To Picking A College Major"](https://fivethirtyeight.com/features/the-economic-guide-to-picking-a-college-major/).

These data originally come from the American Community Survey (ACS) 2010-2012 Public Use Microdata Series.
While this is outside the scope of this assignment, if you are curious about how raw data from the ACS were cleaned and prepared, see [the code](https://github.com/fivethirtyeight/data/blob/master/college-majors/college-majors-rscript.R) FiveThirtyEight authors used.

We should also note that there are many considerations that go into picking a major.
Earnings potential and employment prospects are two of them, and they are important, but they don't tell the whole story.
Keep this in mind as you analyze the data.

In [12]:
file_location = 'https://joannabieri.com/introdatascience/data/recent-grads.csv'
DF_raw = pd.read_csv(file_location)

In [13]:
DF_raw

Rank  Major_code                                      Major    Total  \
0       1        2419                      PETROLEUM ENGINEERING   2339.0   
1       2        2416             MINING AND MINERAL ENGINEERING    756.0   
2       3        2415                  METALLURGICAL ENGINEERING    856.0   
3       4        2417  NAVAL ARCHITECTURE AND MARINE ENGINEERING   1258.0   
4       5        2405                       CHEMICAL ENGINEERING  32260.0   
..    ...         ...                                        ...      ...   
168   169        3609                                    ZOOLOGY   8409.0   
169   170        5201                     EDUCATIONAL PSYCHOLOGY   2854.0   
170   171        5202                        CLINICAL PSYCHOLOGY   2838.0   
171   172        5203                      COUNSELING PSYCHOLOGY   4626.0   
172   173        3501                            LIBRARY SCIENCE   1098.0   

         Men    Women            Major_category  ShareWomen  Sample_size  \
0     2057.0    282.0               Engineering    0.120564           36   
1      679.0     77.0               Engineering    0.101852            7   
2      725.0    131.0               Engineering    0.153037            3   
3     1123.0    135.0               Engineering    0.107313           16   
4    21239.0  11021.0               Engineering    0.341631          289   
..       ...      ...                       ...         ...          ...   
168   3050.0   5359.0    Biology & Life Science    0.637293           47   
169    522.0   2332.0  Psychology & Social Work    0.817099            7   
170    568.0   2270.0  Psychology & Social Work    0.799859           13   
171    931.0   3695.0  Psychology & Social Work    0.798746           21   
172    134.0    964.0                 Education    0.877960            2   

     Employed  ...  Part_time  Full_time_year_round  Unemployed  \
0        1976  ...        270                  1207          37   
1         640  ...        170                   388          85   
2         648  ...        133                   340          16   
3         758  ...        150                   692          40   
4       25694  ...       5180                 16697        1672   
..        ...  ...        ...                   ...         ...   
168      6259  ...       2190                  3602         304   
169      2125  ...        572                  1211         148   
170      2101  ...        648                  1293         368   
171      3777  ...        965                  2738         214   
172       742  ...        237                   410          87   

     Unemployment_rate  Median  P25th   P75th  College_jobs  Non_college_jobs  \
0             0.018381  110000  95000  125000          1534               364   
1             0.117241   75000  55000   90000           350               257   
2             0.024096   73000  50000  105000           456               176   
3             0.050125   70000  43000   80000           529               102   
4             0.061098   65000  50000   75000         18314              4440   
..                 ...     ...    ...     ...           ...               ...   
168           0.046320   26000  20000   39000          2771              2947   
169           0.065112   25000  24000   34000          1488               615   
170           0.149048   25000  25000   40000           986               870   
171           0.053621   23400  19200   26000          2403              1245   
172           0.104946   22000  20000   22000           288               338   

     Low_wage_jobs  
0              193  
1               50  
2                0  
3                0  
4              972  
..             ...  
168            743  
169             82  
170            622  
171            308  
172            192  

[173 rows x 21 columns]

### 1. Describe the data that you see here.

* How many variables?
* How man observations?
* Are the variables categorical or numerical?
* Are there any variables that you don't know what they mean? If so [CLICK HERE - to see the Git Repo for the data where the variables are defined](https://github.com/fivethirtyeight/data/tree/master/college-majors)


In [14]:
#

In [15]:
#

In [16]:
#

**(Click Here to Explain your Results)**

### 2. Answer some questions about the data

* Which major has the lowest unemployment rate? Show a data frame that answers this question, but only show columns that are useful to the answer.
* Which major has the highest percentage of women? Show a data frame that answers this question, but only show columns that are useful to the answer.
* How do the distributions of median income compare across major categories?
    * First get a value count on what major categories are in the data. What categories are most or least represented?
    * Do some summary statistics using the .group_by() command to see the statistics for each major category.
    * Make a histogram that explores median income for each of the major categories (facet_col). How did you choose your number of bins?
    * Why do we often choose the median, rather than the mean, to describe the typical income of a group of people? Look this up online if you don't know the answer!
    * Answer the question: Which major category has the highest typical (you'll need to decide what this means) median income?

In [17]:
#

In [18]:
#

In [19]:
#

**(Click Here to Explain your Results)**

### 3. More complicated questions

* Are all STEM fields the same in terms job opportunities?
    * Assume the following are STEM major categories
    
  ``` ["Biology & Life Science", "Computers & Mathematics", "Engineering","Physical Sciences"]```
  
    * Create a DataFrame (using a mask) so you only look at STEM majors.
    * Which STEM majors have median salaries equal to or less than the median for all majors' median earnings?
* What types of majors do women tend to major in?
    * Create a scatterplot of median income vs. proportion of women in that major, coloured by whether the major is in a STEM field or not.

In [22]:
#mask needs to include the 4 majors

mask = (DF_raw['Major_category']=='Biology & Life Science') | (DF_raw['Major_category']=='Computers & Mathematics') | (DF_raw['Major_category']=='Engineering') | (DF_raw['Major_category']=='Physical Sciences')
DF_stem = DF_raw[mask]
DF_stem

Rank  Major_code                                      Major     Total  \
0       1        2419                      PETROLEUM ENGINEERING    2339.0   
1       2        2416             MINING AND MINERAL ENGINEERING     756.0   
2       3        2415                  METALLURGICAL ENGINEERING     856.0   
3       4        2417  NAVAL ARCHITECTURE AND MARINE ENGINEERING    1258.0   
4       5        2405                       CHEMICAL ENGINEERING   32260.0   
..    ...         ...                                        ...       ...   
110   111        5002       ATMOSPHERIC SCIENCES AND METEOROLOGY    4043.0   
122   123        3699                      MISCELLANEOUS BIOLOGY   10706.0   
123   124        3600                                    BIOLOGY  280709.0   
132   133        3604                                    ECOLOGY    9154.0   
168   169        3609                                    ZOOLOGY    8409.0   

          Men     Women          Major_category  ShareWomen  Sample_size  \
0      2057.0     282.0             Engineering    0.120564           36   
1       679.0      77.0             Engineering    0.101852            7   
2       725.0     131.0             Engineering    0.153037            3   
3      1123.0     135.0             Engineering    0.107313           16   
4     21239.0   11021.0             Engineering    0.341631          289   
..        ...       ...                     ...         ...          ...   
110    2744.0    1299.0       Physical Sciences    0.321296           32   
122    4747.0    5959.0  Biology & Life Science    0.556604           63   
123  111762.0  168947.0  Biology & Life Science    0.601858         1370   
132    3878.0    5276.0  Biology & Life Science    0.576360           86   
168    3050.0    5359.0  Biology & Life Science    0.637293           47   

     Employed  ...  Part_time  Full_time_year_round  Unemployed  \
0        1976  ...        270                  1207          37   
1         640  ...        170                   388          85   
2         648  ...        133                   340          16   
3         758  ...        150                   692          40   
4       25694  ...       5180                 16697        1672   
..        ...  ...        ...                   ...         ...   
110      3431  ...       1309                  2161          78   
122      7767  ...       2568                  4542         483   
123    182295  ...      72371                100336       13874   
132      7585  ...       2741                  3912         437   
168      6259  ...       2190                  3602         304   

     Unemployment_rate  Median  P25th   P75th  College_jobs  Non_college_jobs  \
0             0.018381  110000  95000  125000          1534               364   
1             0.117241   75000  55000   90000           350               257   
2             0.024096   73000  50000  105000           456               176   
3             0.050125   70000  43000   80000           529               102   
4             0.061098   65000  50000   75000         18314              4440   
..                 ...     ...    ...     ...           ...               ...   
110           0.022229   35000  28000   50000          1808              1317   
122           0.058545   33500  23000   48000          4253              2722   
123           0.070725   33400  24000   45000         88232             81109   
132           0.054475   33000  23000   42000          2856              4159   
168           0.046320   26000  20000   39000          2771              2947   

     Low_wage_jobs  
0              193  
1               50  
2                0  
3                0  
4              972  
..             ...  
110            237  
122            459  
123          28339  
132            976  
168            743  

[64 rows x 21 columns]

In [28]:
#median for total, stem, individual stem
mall = DF_raw['Median'].median()
print(mall)
mstem = DF_stem['Median'].median()
print(mstem)

36000.0
45000.0


In [29]:
#["Biology & Life Science", "Computers & Mathematics", "Engineering","Physical Sciences"]
mstem = DF_stem['Median'].median()
print(mstem)

major_cat = 'Biology & Life Science'
mask = DF_stem['Major_category'] == major_cat
cat_median = DF_stem[mask]['Median'].median()
print(cat_median)

45000.0
36300.0


In [30]:
DF_raw.keys()

Index(['Rank', 'Major_code', 'Major', 'Total', 'Men', 'Women',
       'Major_category', 'ShareWomen', 'Sample_size', 'Employed', 'Full_time',
       'Part_time', 'Full_time_year_round', 'Unemployed', 'Unemployment_rate',
       'Median', 'P25th', 'P75th', 'College_jobs', 'Non_college_jobs',
       'Low_wage_jobs'],
      dtype='object')

In [40]:
mcol = ['Major', 'Major_category', 'ShareWomen']

DF_raw[mcol].sort_values(by = 'ShareWomen', ascending = False).head(25)

fig = px.scatter(DF_raw, x='Median', y='ShareWomen')


AttributeError: module 'plotly.express' has no attribute 'show'

**(Click Here to Explain your Results)**

***The median is overall higher but not all stem is created equal. bio + stem is 36300.0, which is slightly higher than the median for all which is 36000.0.***

### 4. Ask a question of interest to you.

In [24]:
#

**(Click Here to Explain your Results)**